name: flutter_animation_set
description: Easy to build an animation set
version: 0.0.5
author: AndroidHensen <xyj510402535@qq.com>
homepage: https://github.com/efoxTeam/flutter-animation-set

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: yy.inc.flutter_animation_set
    pluginClass: FlutterAnimationSetPlugin